# Generated by Django 4.0.4 on 2022-05-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
